# Generated by Django 2.1.2 on 2018-11-19 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import manga.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('title_roman', models.CharField(blank=True, default='', max_length=191)),
                ('title_kanji', models.CharField(blank=True, default='', max_length=191)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('picture', sorl.thumbnail.fields.ImageField(blank=True, default='img/manga/default/brak_obrazka.jpg', upload_to=manga.models.user_directory_path)),
                ('type_series', models.CharField(choices=[('Doujin', 'Doujin'), ('Manga', 'Manga'), ('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Light Novel', 'Light Novel'), ('One Shot', 'One Shot')], default='', max_length=5)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status_anime', models.CharField(choices=[('Publikowane', 'Publikowane'), ('Zapowiedź', 'Zapowiedź'), ('Zakończone', 'Zakończone')], default='', max_length=20)),
                ('mpaa', models.CharField(choices=[('', '--'), ('G', 'G - Wszystkie grupy wiekowe'), ('PG', 'PG - Materiał nieodpowiedni dla dzieci'), ('PG-13', 'PG-13 - Materiał dla osób powyżej 13 roku życia'), ('R', 'R - Materiały dla osób powyżej 17 roku życia (przemoc, wulgaryzmy)'), ('R+', 'R+ - Niektóre materiały mogą być nieodpowiednie dla osób poniżej 17 roku życia, zawiera nagość'), ('Rx', 'Rx - Materiały są nieodpowiednie dla osób poniżej 18 roku życia, zawierają pornografię'), ('Ry', 'Ry - Materiały są nieodpowiednie dla osób poniżej 18 roku życia, zawierają homoseksualną pornografię')], default='', max_length=5)),
                ('number_tom', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('number_chapter', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScoreManga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('story', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('character', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('graphics', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('music', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('manga_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='manga.Manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scoremanga',
            unique_together={('user', 'manga_title')},
        ),
    ]
