# Generated by Django 2.1.2 on 2018-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadow', '0002_remove_likedislike_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationanime',
            name='votes',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='recom',
            field=models.ManyToManyField(to='shadow.RecommendationAnime'),
        ),
    ]
