# Generated by Django 2.1.2 on 2018-11-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shadow', '0003_auto_20181119_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='recom',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='recom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shadow.RecommendationAnime'),
            preserve_default=False,
        ),
    ]
