# Generated by Django 2.1.2 on 2018-11-19 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('type', models.CharField(choices=[('Gatunki', 'Gatunki'), ('Grupy docelowa', 'Grupy docelowa'), ('Rodzaje postaci', 'Rodzaje postaci'), ('Miejsce i czas', 'Miejsce i czas'), ('Pozostałe tagi', 'Pozostałe tagi'), ('Studio', 'Studio'), ('Typy produkcji', 'Typy produkcji'), ('Wydawnictwa', 'Wydawnictwa'), ('Pierwowzór', 'Pierwowzór')], max_length=20)),
                ('language', models.CharField(default='Polski', editable=False, max_length=6)),
                ('parent', models.CharField(blank=True, default=' ', max_length=191, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('Published', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'type')},
        ),
    ]
